export const data_1= [
  { 
  id: 1,
  publisher: 'john',
  title:'Lorem ipsum dolor sit amet',
  host:'ECOLE SUPERIEUR EN INFORMATIQUE SIDI-BEL-ABBES, Algeria',
  adresse:'consectetur adipiscing elit. Vestibulum id velit enim. Nulla egestas enim tortor',
  description:'a fringilla metus tincidunt sed. Vivamus auctor, mi et aliquam placerat, tortor augue blandit tellus, mattis luctus diam nulla at libero. Aliquam viverra scelerisque pulvinar. In vel ligula suscipit diam imperdiet dictum. Maecenas mollis nisl nunc, vitae venenatis odio sodales sed. Curabitur vel mi non eros egestas laoreet. Sed ultricies rutrum dolor vel lacinia. Mauris at aliquet neque. In hac habitasse platea dictumst. Suspendisse efficitur dolor id ex rutrum commodo. Vivamus id tellus non metus luctus rutrum. Nam auctor nisl neque, pellentesque tempor turpis varius id.',
  photo:'https://traconference.eu/wp-content/uploads/2021/08/pexels-luis-quintero-2833037-scaled-e1629113060469.jpg',
  category:'mattis tempo',
  startDate:'2021-15-3',
  endate:'2022-16-2'
 },
 { 
  id: 3,
  publisher: 'maria',
  title:'Nunc varius in massa vitae facilisis',
  host:'ECOLE SUPERIEUR EN INFORMATIQUE SIDI-BEL-ABBES, Algeria',
  adresse:'quam est mollis risus, sollicitudin',
  description:'Mauris ut pharetra augue, at semper tortor. Donec tristique, ligula at blandit iaculis, quam est mollis risus, sollicitudin auctor elit tellus id mauris. Nulla pulvinar turpis quis tempor fringilla. Vestibulum a nisl vel odio porttitor dapibus ac vitae libero. Nulla semper mattis tortor, sit amet dictum metus.',
  photo:'https://traconference.eu/wp-content/uploads/2021/08/pexels-luis-quintero-2833037-scaled-e1629113060469.jpg',
  category:'non pharetra turpis',
  startDate:'2000-1-1',
  endate:'2002-11-1'
 },
 { 
  id: 2,
  publisher: 'anna',
  title:'purus enim',
  host:'ECOLE SUPERIEUR EN INFORMATIQUE SIDI-BEL-ABBES, Algeria',
  adresse:'quis tempor ante. Mauris ut pharetra augue',
  description:'lacus ligula eu tellus. Nunc varius in massa vitae facilisis. Donec semper aliquet purus, non mattis velit egestas non. Fusce eget ultrices sapien, at gravida lorem. Pellentesque placerat, ante ut finibus tincidunt, sapien ipsum euismod dolor, vel tristique magna sapien a sapien.',
  photo:'https://traconference.eu/wp-content/uploads/2021/08/pexels-luis-quintero-2833037-scaled-e1629113060469.jpg',
  category:'Sed ac massa id',
  startDate:'2024-1-4',
  endate:'2028-5-5'
 },
 { 
  id: 4,
  publisher: 'hmida',
  title:'Vestibulum a nisl vel odio porttitor dapibus',
  host:'ECOLE SUPERIEUR EN INFORMATIQUE SIDI-BEL-ABBES, Algeria',
  adresse:'Praesent laoreet, elit sed gravida lobortis, purus nisi dignissim dui, eu fringilla',
  description:'lacus ligula eu tellus. Nunc varius in massa vitae facilisis. Donec semper aliquet purus, non mattis velit egestas non. Fusce eget ultrices sapien, at gravida lorem. Pellentesque placerat, ante ut finibus tincidunt, sapien ipsum euismod dolor, vel tristique magna sapien a sapien. Curabitur commodo pharetra dui in cursus. Sed felis mi, pretium ut dignissim eget, faucibus at ligula.',
  photo:'https://traconference.eu/wp-content/uploads/2021/08/pexels-luis-quintero-2833037-scaled-e1629113060469.jpg',
  category:'sit amet, faucibus',
  startDate:'2009-9-9',
  endate:'2010-4-5'
 },
 { 
  id: 5,
  publisher: 'houari',
  title:'Vivamus id tellus non metus luctus rutrum',
  host:'ECOLE SUPERIEUR EN INFORMATIQUE SIDI-BEL-ABBES, Algeria',
  adresse:'Curabitur commodo pharetra dui in cursus. Sed felis mi',
  description:'Maecenas id lectus a lacus rutrum mollis. Sed ac massa id magna pharetra lacinia. Aenean pulvinar nisl et dolor tincidunt, eu tristique justo tincidunt. Fusce et rutrum est. Suspendisse eget dolor venenatis, commodo velit quis, aliquam arcu. Duis consectetur, arcu nec rutrum lacinia, sem est consequat turpis, non pharetra turpis lectus sit amet ex. In ipsum felis, vehicula eu eleifend a, molestie non ipsum.',
  photo:'https://traconference.eu/wp-content/uploads/2021/08/pexels-luis-quintero-2833037-scaled-e1629113060469.jpg',
  category:'tempor. Nunc ',
  startDate:'2007-4-7',
  endate:'2009-3-1'
 },
];

export const users = [
  {
    id: 6,
    first_name: "hfdubrd",
    family_name: "string",
    email: "user@example.com",
    phone_number: "string",
    full_adress: "string",
    linked_in_username: "string",
    fields_of_interssts: "string",
    bio: "this is bio",
    profile_picture: "http://127.0.0.1:8000/media/profile_pictures/consult-declar_nKXwXRI.png",
    is_admin: false
  },
  {
    id: 7,
    first_name: "hfdubrd",
    family_name: "string",
    email: "user@example.com",
    phone_number: "string",
    full_adress: "string",
    linked_in_username: "string",
    fields_of_interssts: "string",
    bio: "this is bio",
    profile_picture: "http://127.0.0.1:8000/media/profile_pictures/consult-declar_nKXwXRI.png",
    is_admin: false
  },
  {
    id: 8,
    first_name: "hfdubrd",
    family_name: "string",
    email: "user@example.com",
    phone_number: "string",
    full_adress: "string",
    linked_in_username: "string",
    fields_of_interssts: "string",
    bio: "this is bio",
    profile_picture: "http://127.0.0.1:8000/media/profile_pictures/consult-declar_nKXwXRI.png",
    is_admin: false
  },
  {
    id:9,
    first_name: "hfdubrd",
    family_name: "string",
    email: "user@example.com",
    phone_number: "string",
    full_adress: "string",
    linked_in_username: "string",
    fields_of_interssts: "string",
    bio: "this is bio",
    profile_picture: "http://127.0.0.1:8000/media/profile_pictures/consult-declar_nKXwXRI.png",
    is_admin: false
  },
  {
    id: 10,
    first_name: "hfdubrd",
    family_name: "string",
    email: "user@example.com",
    phone_number: "string",
    full_adress: "string",
    linked_in_username: "string",
    fields_of_interssts: "string",
    bio: "this is bio",
    profile_picture: "http://127.0.0.1:8000/media/profile_pictures/consult-declar_nKXwXRI.png",
    is_admin: false
  },
  {
    id: 11,
    first_name: "hfdubrd",
    family_name: "string",
    email: "user@example.com",
    phone_number: "string",
    full_adress: "string",
    linked_in_username: "string",
    fields_of_interssts: "string",
    bio: "this is bio",
    profile_picture: "http://127.0.0.1:8000/media/profile_pictures/consult-declar_nKXwXRI.png",
    is_admin: false
  },
  { 
    id: 12,
    publisher: 'john',
    title:'Lorem ipsum dolor sit amet',
    host:'ECOLE SUPERIEUR EN INFORMATIQUE SIDI-BEL-ABBES, Algeria',
    adresse:'consectetur adipiscing elit. Vestibulum id velit enim. Nulla egestas enim tortor',
    description:'a fringilla metus tincidunt sed. Vivamus auctor, mi et aliquam placerat, tortor augue blandit tellus, mattis luctus diam nulla at libero. Aliquam viverra scelerisque pulvinar. In vel ligula suscipit diam imperdiet dictum. Maecenas mollis nisl nunc, vitae venenatis odio sodales sed. Curabitur vel mi non eros egestas laoreet. Sed ultricies rutrum dolor vel lacinia. Mauris at aliquet neque. In hac habitasse platea dictumst. Suspendisse efficitur dolor id ex rutrum commodo. Vivamus id tellus non metus luctus rutrum. Nam auctor nisl neque, pellentesque tempor turpis varius id.',
    photo:'https://traconference.eu/wp-content/uploads/2021/08/pexels-luis-quintero-2833037-scaled-e1629113060469.jpg',
    category:'mattis tempo',
    startDate:'2021-15-3',
    endate:'2022-16-2'
   },
   { 
    id: 13,
    publisher: 'maria',
    title:'Nunc varius in massa vitae facilisis',
    host:'ECOLE SUPERIEUR EN INFORMATIQUE SIDI-BEL-ABBES, Algeria',
    adresse:'quam est mollis risus, sollicitudin',
    description:'Mauris ut pharetra augue, at semper tortor. Donec tristique, ligula at blandit iaculis, quam est mollis risus, sollicitudin auctor elit tellus id mauris. Nulla pulvinar turpis quis tempor fringilla. Vestibulum a nisl vel odio porttitor dapibus ac vitae libero. Nulla semper mattis tortor, sit amet dictum metus.',
    photo:'https://traconference.eu/wp-content/uploads/2021/08/pexels-luis-quintero-2833037-scaled-e1629113060469.jpg',
    category:'non pharetra turpis',
    startDate:'2000-1-1',
    endate:'2002-11-1'
   },
   { 
    id: 14,
    publisher: 'anna',
    title:'purus enim',
    host:'ECOLE SUPERIEUR EN INFORMATIQUE SIDI-BEL-ABBES, Algeria',
    adresse:'quis tempor ante. Mauris ut pharetra augue',
    description:'lacus ligula eu tellus. Nunc varius in massa vitae facilisis. Donec semper aliquet purus, non mattis velit egestas non. Fusce eget ultrices sapien, at gravida lorem. Pellentesque placerat, ante ut finibus tincidunt, sapien ipsum euismod dolor, vel tristique magna sapien a sapien.',
    photo:'https://traconference.eu/wp-content/uploads/2021/08/pexels-luis-quintero-2833037-scaled-e1629113060469.jpg',
    category:'Sed ac massa id',
    startDate:'2024-1-4',
    endate:'2028-5-5'
   },
   { 
    id: 15,
    publisher: 'hmida',
    title:'Vestibulum a nisl vel odio porttitor dapibus',
    host:'ECOLE SUPERIEUR EN INFORMATIQUE SIDI-BEL-ABBES, Algeria',
    adresse:'Praesent laoreet, elit sed gravida lobortis, purus nisi dignissim dui, eu fringilla',
    description:'lacus ligula eu tellus. Nunc varius in massa vitae facilisis. Donec semper aliquet purus, non mattis velit egestas non. Fusce eget ultrices sapien, at gravida lorem. Pellentesque placerat, ante ut finibus tincidunt, sapien ipsum euismod dolor, vel tristique magna sapien a sapien. Curabitur commodo pharetra dui in cursus. Sed felis mi, pretium ut dignissim eget, faucibus at ligula.',
    photo:'https://traconference.eu/wp-content/uploads/2021/08/pexels-luis-quintero-2833037-scaled-e1629113060469.jpg',
    category:'sit amet, faucibus',
    startDate:'2009-9-9',
    endate:'2010-4-5'
   },
   { 
    id: 16,
    publisher: 'houari',
    title:'Vivamus id tellus non metus luctus rutrum',
    host:'ECOLE SUPERIEUR EN INFORMATIQUE SIDI-BEL-ABBES, Algeria',
    adresse:'Curabitur commodo pharetra dui in cursus. Sed felis mi',
    description:'Maecenas id lectus a lacus rutrum mollis. Sed ac massa id magna pharetra lacinia. Aenean pulvinar nisl et dolor tincidunt, eu tristique justo tincidunt. Fusce et rutrum est. Suspendisse eget dolor venenatis, commodo velit quis, aliquam arcu. Duis consectetur, arcu nec rutrum lacinia, sem est consequat turpis, non pharetra turpis lectus sit amet ex. In ipsum felis, vehicula eu eleifend a, molestie non ipsum.',
    photo:'https://traconference.eu/wp-content/uploads/2021/08/pexels-luis-quintero-2833037-scaled-e1629113060469.jpg',
    category:'tempor. Nunc ',
    startDate:'2007-4-7',
    endate:'2009-3-1'
   },

    {
      id: 17,
      first_name: "hfdubrd",
      family_name: "string",
      email: "user@example.com",
      phone_number: "string",
      full_adress: "string",
      linked_in_username: "string",
      fields_of_interssts: "string",
      bio: "this is bio",
      profile_picture: "http://127.0.0.1:8000/media/profile_pictures/consult-declar_nKXwXRI.png",
      is_admin: false
    },
    {
      id: 18,
      first_name: "hfdubrd",
      family_name: "string",
      email: "user@example.com",
      phone_number: "string",
      full_adress: "string",
      linked_in_username: "string",
      fields_of_interssts: "string",
      bio: "this is bio",
      profile_picture: "http://127.0.0.1:8000/media/profile_pictures/consult-declar_nKXwXRI.png",
      is_admin: false
    },
    {
      id: 19,
      first_name: "hfdubrd",
      family_name: "string",
      email: "user@example.com",
      phone_number: "string",
      full_adress: "string",
      linked_in_username: "string",
      fields_of_interssts: "string",
      bio: "this is bio",
      profile_picture: "http://127.0.0.1:8000/media/profile_pictures/consult-declar_nKXwXRI.png",
      is_admin: false
    }
];
